## 
# File: roles/common/tasks/common.yml
# Incommon tasks needed by other roles
# Author: Hikmat Dhamee
##

---
- name: Fetch HDP repo
  shell: "echo hello"
  shell: "wget -nv http://public-repo-1.hortonworks.com/HDP/centos6/2.x/updates/2.0.6.0/hdp.repo -O /etc/yum.repos.d/hdp.repo creates=/etc/yum.repos.d/hdp.repo"

#- name: Download JDK
#  shell: "wget --quiet --no-cookies -O {{ jdk_rpm }} --header 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com;' {{ jdk_download_url }} --no-check-certificate creates={{ jdk_rpm }}"
#
#- name: Install JDK
#  shell: "yum -y --nogpgcheck localinstall {{ jdk_rpm }} creates=/usr/java"
# sudo: yes
#
#- name: Create a link for java
#  file: src=/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0.x86_64/jre state=link path=/usr/java/default
#  sudo: yes

- name: Install the openjdk package
  yum: name=java-1.6.0-openjdk state=installed

- name: Create a directory for java
  file: state=directory path=/usr/java/

- name: Create a link for java
  file: src=/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.0.x86_64/jre state=link path=/usr/java/default

- name: Install SElinux ansible module dependencies
  yum: name=libselinux-python state=installed

- name: Disable SELinux in conf file
  selinux: state=disabled