##
# File: roles/hdp-yarn-nodemanager/tasks/main.yml 
# Install the hadoop packages for yarn-nodemanager
# Author: Hikmat Dhamee
##

---
- name: Install hadoop-yarn-nodemanager
  yum: name={{ item }} state=installed
  with_items:
    - hadoop-yarn-nodemanager
  sudo: yes

- name: create the yarn local directory
  file: path={{ item }} owner=yarn group=yarn state=directory
  with_items:
    - hadoop.YARN_LOCAL_DIR
  sudo: yes

- name: create the yarn logs directory
  file: path={{ item }} owner=yarn group=yarn state=directory
  with_items:
    - hadoop.YARN_LOG_DIR
  sudo: yes

- name: Copy the hadoop configuration files
  template: src=hadoop_conf/{{ item }}.j2 dest=/etc/hadoop/conf/{{ item }} mode=644
  with_items:
   - core-site.xml
   - hdfs-site.xml
   - mapred-site.xml
   - yarn-site.xml
   - log4j.properties
   - capacity-scheduler.xml
   - commons-logging.properties
   - container-executor.cfg
   - hadoop-env.sh
   - yarn-env.sh
   - hadoop-metrics2.properties
   - hadoop-metrics2.properties-GANGLIA
   - hadoop-policy.xml
   - health_check
   - slaves
   - mapred-queue-acls.xml 
  sudo: yes
  notify:
   - Start Node Manager on datanodes