##
# File: roles/hdp-namenode/tasks/main.yml 
# Install the hadoop packages for namenode
# Author: Hikmat Dhamee
##

---
- name: Install hadoop-hdfs-namenode components
  yum: name={{ item }} state=installed
  with_items:
    - hadoop-hdfs-namenode
  sudo: yes

- name: Create the data directory for the namenode metadata
  file: path={{ item }} owner={{ hadoop.HDFS_USER }} group=hdfs state=directory
  with_items: hadoop.DFS_NAMENODE_DIR

- name: Create the log directory for the namenode metadata
  file: path={{ item }} owner={{ hadoop.HDFS_USER }} group=hdfs state=directory
  with_items: hadoop.HDFS_LOG_DIR

- name: Create the pid directory for the namenode metadata
  file: path={{ item }} owner={{ hadoop.HDFS_USER }} group=hdfs state=directory
  with_items: hadoop.HDFS_PID_DIR

- name: Copy the hadoop configuration files
  template: src=hadoop_conf/{{ item }}.j2 dest=/etc/hadoop/conf/{{ item }} mode=0644
  with_items:
   - core-site.xml
   - hdfs-site.xml
   - mapred-site.xml
   - yarn-site.xml
   - log4j.properties
   - capacity-scheduler.xml
   - commons-logging.properties
   - container-executor.cfg
   - hadoop-env.sh
   - yarn-env.sh
   - hadoop-metrics2.properties
   - hadoop-metrics2.properties-GANGLIA
   - hadoop-policy.xml
   - health_check
   - slaves
   - mapred-queue-acls.xml 
  sudo: yes
  notify: 
   - Format the namenode
   - Start hadoop namenode services