##
# File: roles/hdp-namenode/tasks/main.yml 
# Install the hadoop packages for namenode
# Author: Hikmat Dhamee
##

---
- name: Install hadoop-hdfs-namenode components
  yum: name={{ item }} state=installed
  with_items:
    - hadoop-hdfs-namenode
  sudo: yes

- name: Create the data directory for the namenode metadata
  file: path={{ item }} owner={{ hadoop.HDFS_USER }} group=hdfs state=directory
  with_items: hadoop.DFS_NAMENODE_DIR

- name: Create the log directory for the namenode metadata
  file: path={{ item }} owner={{ hadoop.HDFS_USER }} group=hdfs state=directory
  with_items: hadoop.HDFS_LOG_DIR

- name: Create the pid directory for the namenode metadata
  file: path={{ item }} owner={{ hadoop.HDFS_USER }} group=hdfs state=directory
  with_items: hadoop.HDFS_PID_DIR

- name: Copy the hadoop configuration files
  template: src=hadoop_conf/{{ item }}.j2 dest=/etc/hadoop/conf/{{ item }} mode=0644
  with_items:
   - core-site.xml
   - hdfs-site.xml
   - mapred-site.xml
   - yarn-site.xml
   - log4j.properties
   - capacity-scheduler.xml
   - commons-logging.properties
   - container-executor.cfg
   - hadoop-env.sh
   - yarn-env.sh
   - hadoop-metrics2.properties
   - hadoop-metrics2.properties-GANGLIA
   - hadoop-policy.xml
   - health_check
   - slaves
   - mapred-queue-acls.xml 
  sudo: yes
  notify: 
   - Format the namenode
   - Start hadoop namenode services

- name: Create HDFS /tmp  /var  and  /user dirs
  action: >
      command sudo -u hdfs hadoop fs -mkdir -p
      /tmp
      /tmp/hadoop-yarn
      /tmp/hadoop-yarn/staging
      /tmp/hadoop-yarn/staging/history
      /var
      /var/log
      /var/log/hadoop-yarn
      /var/log/hadoop-yarn/apps
      /user/history
    
- name: Set HDFS permissions
  action: |
      command sudo -u hdfs -- /bin/sh -c '
      hadoop fs -chmod -R 1777 /tmp
      hadoop fs -chown -R yarn /tmp/hadoop-yarn
      hadoop fs -chmod -R 755 /var
      hadoop fs -chown -R yarn:mapred /var/log/hadoop-yarn
      hadoop fs -chmod -R 755 /user
      hadoop fs -chmod 1777 /user/history'