#
# Copy the hadoop configuration files
# Author: Hikmat Dhamee
#

---
- name: Copy the hadoop configuration files
  template: src=hadoop_conf/{{ item }}.j2 dest=/etc/hadoop/conf/{{ item }}
  with_items:
   - core-site.xml
   - hdfs-site.xml
   - mapred-site.xml
   - yarn-site.xml
   - log4j.properties
   - capacity-scheduler.xml
   - commons-logging.properties
   - container-executor.cfg
   - hadoop-env.xml
   - yarn-env.sh
   - hadoop-metrics2.properties
   - hadoop-metrics2.properties-GANGLIA
   - hadoop-policy.xml
   - health-check
   - mapred-queue-cls.xml 
  sudo: yes

# creating necessary directories for hadoop components
- name: Create the data directory for the namenode datanode secondarynamenode yarn and for pid
  file: path={{ item }} owner=hdfs group=hdfs state=directory
  with_items: 
   - DFS_NAME_DIR
   - DFS_DATA_DIR
   - FS_CHECKPOINT_DIR
   - HDFS_LOG_DIR
   - HDFS_PID_DIR
   - HADOOP_CONF_DIR
   - YARN_LOCAL_DIR
   - YARN_LOCAL_LOG_DIR
   - YARN_PID_DIR
   - MAPRED_LOG_DIR
   - MAPRED_PID_DIR
  sudo: yes
  notify: 
       - format the namenode
       - start hadoop namenode services