##
# File: hdp-stop.yml
# Ansible playbook to stop HDP cluster
# USAGE:: $ ansible-playbook -i [stage|production] hdp-stop.yml
# Author: Hikmat Dhamee
##

---
# Stop HDFS 
- hosts: namenodes
  tasks:
    - name: stop hadoop namenode services
      service: name=hadoop-hdfs-namenode state=stoped
      sudo: yes

- hosts: datanodes
  tasks:
    - name: Stop HDFS on datanodes
      service: name=hadoop-hdfs-datanode state=stoped
      sudo: yes

    # Stop YARN
- hosts: resourcemanagers
  tasks:
    - name: Stop Resource Manager
      service: name=hadoop-yarn-resourcemanager state=stoped
      sudo: yes
- hosts: nademanagers
  tasks:
    - name: Stop Node Manager on datanodes
      service: name=hadoop-yarn-nodemanager state=stoped
      sudo: yes

- hosts: historyservers
  tasks:
     - name: Stop History Server
       service: name=hadoop-mapreduce-historyserver state=stoped
       sudo: yes
