# ##
# # This is a ansible play book to deploy HDP cluster
# # Usage: $ansible-playbook -i [stage|production] site.yml
# # Author: Hikmat Dhamee
# ##

---
- hosts: cluster
  roles:
   - common
   - hdp-common

- hosts: datanodes
  roles:
   - hdp-datanode

- hosts: namenodes
  roles:
   - hdp-namenode

- hosts: historyservers
  roles:
   - hdp-mapreduce-historyserver

- hosts: nodemanagers
  roles:
   - hdp-yarn-nodemanager

- hosts: resourcemanagers
  roles:
   - hdp-yarn-resourcemanager