#
# Handlers for the hadoop master services
# Author: Hikmat Dhamee
#

---
# Start HDFS
- name: format the namenode
  shell: creates=/usr/lib/hadoop/namenode.formatted su - hdfs -c "hadoop namenode -format" && touch /usr/lib/hadoop/namenode.formatted
  sudo: yes

- name: start hadoop namenode services
  service: name=hadoop-hdfs-namenode state=started
  sudo: yes

- name: Start HDFS on datanodes
  service: name=hadoop-hdfs-datanode state=started
  sudo: yes

# Start MapReduce.
- name: Start Resource Manager
  service: name=hadoop-yarn-resourcemanager state=started
  sudo: yes

- name: Start Node Manager on datanodes
  service: name=hadoop-yarn-nodemanager state=started
  sudo: yes

- name: Start History Server
  service: name=hadoop-mapreduce-historyserver state=started
  sudo: yes