##
# File: roles/hdp-mapreduce-historyserver/tasks/main.yml 
# Install the hadoop-mapreduce-historyserver package
# Author: Hikmat Dhamee
##

---
- name: Install hadoop-mapreduce-historyserver
  yum: name={{ item }} state=installed
  with_items:
   - hadoop-mapreduce-historyserver
  sudo: yes

- name: Copy the hadoop configuration files
  template: src=hadoop_conf/{{ item }}.j2 dest=/etc/hadoop/conf/{{ item }} mode=644
  with_items:
   - core-site.xml
   - hdfs-site.xml
   - mapred-site.xml
   - yarn-site.xml
   - log4j.properties
   - capacity-scheduler.xml
   - commons-logging.properties
   - container-executor.cfg
   - hadoop-env.sh
   - yarn-env.sh
   - hadoop-metrics2.properties
   - hadoop-metrics2.properties-GANGLIA
   - hadoop-policy.xml
   - health_check
   - slaves
   - mapred-queue-acls.xml 
  sudo: yes
  notify:
   - Start History Server